### ISSUE TITLE
Support `ArchiveType` for Assets

### ISSUE THREAD

**Issue by noah-severyn** [noah-severyn/YamlEditorForSc4pac#44]
See [here](https://memo33.github.io/sc4pac/#/metadata?id=archivetype). Example:
```yaml
archiveType:
  format: Clickteam
  version: "40"  # possible versions are 40, 35, 30, 24, 20
```
