### ISSUE TITLE
Regex strings are properly escaped when parsed

### ISSUE THREAD

**Issue by noah-severyn** [noah-severyn/YamlEditorForSc4pac#66]
```yaml
assets:
- assetId: "peg-utopia-collection"
  include:
  - "\/Utopia\/SkyFarms\/.*(Landmark)"
```
Regex strings either get double escaped or have the escape character removed when parsed and dumped.
