### ISSUE TITLE
Update variant description format

### ISSUE THREAD

**Issue by noah-severyn** [noah-severyn/YamlEditorForSc4pac#98]
New variant format, including a description for the variant itself, in addition to the value. The old `variantDescription` block is obsolete and should be reformatted into this new block. See memo33/sc4pac-actions/issues/2 for more info. New format is 
```yaml
variantInfo:
  - variantId: nightmode
    description: ""         # new, optional
    values:                 # optional
      - value: standard
        description: ""
        default: true       # new, optional
      - value: dark
        description: ""
  - variantId: driveside
    description: ""
    values:
      - value: right
        description: ""
      - value: left
        description: ""
```
